### ISSUE TITLE
Argument 3 error after 2.0.3 upgrade

### ISSUE THREAD

**Issue by CitizenBeta** [dillingham/nova-ajax-select#3]
Thanks for the awesome package! Very much appreciated.

After the most recent Nova upgrade, I get this error:

> local.ERROR: Argument 3 passed to Laravel\Nova\Fields\Field::__construct() must be callable or null, string given, called in/vendor/laravel/nova/src/Element.php on line 46 {"userId":5,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 3 passed to Laravel\\Nova\\Fields\\Field::__construct() must be callable or null, string given, called in /vendor/laravel/nova/src/Element.php on line 46 at /vendor/laravel/nova/src/Fields/Field.php:144

Here's my code which did work before:

```
AjaxSelect::make('Location', 'brandLocation', 'App\Nova\Brands\Locations\BrandLocation')->onlyOnForms()
                ->get('/api/nova/brands/{brand}/locations')
                ->parent('brand'),
```

Any assistance would be greatly appreciated. Maybe I'm doing something wrong?

**Comment by dillingham** [comment]
Hey thanks, I’ll take a look

**Comment by CitizenBeta** [comment]
After some experimentation, I think in the recent update, Nova removed the 3rd resource argument for custom fields which makes sense since the custom field might not need it. In this package's case, it doesn't make use of the resource definition so it's safe to just remove it, whereas it's normally required for a traditional Nova BelongsTo relationship if you have to specify the relationship. I removed it so now my code looks like this:

```
AjaxSelect::make('Location', 'brandLocation')->onlyOnForms()
                ->get('/api/nova/brands/{brand}/locations')
                ->parent('brand'),
```

And it works great again. Thanks Dillingham for this package, working perfectly as far as I can tell. Close the issue?

**Comment by dillingham** [comment]
@CitizenBeta Yeah the field is essentially a text field and so the 3rd parameter currently acts as a callback for display.. whereas in a belongs to, its the resource to display. If this package were explicitly a BelongsTo field that would make perfect sense.. 

I didn't catch this personally because I was using it like so:

```php
AjaxSelect::make('User', 'user_id'),
BelongsTo::make('User')
```
(Because it currently doesnt have a detail / index view)

Let's leave this open as it might make sense to add support for it to render detail / index

**Comment by CitizenBeta** [comment]
@dillingham But isn't that covered by the API output that populates the dropdown?

**Comment by dillingham** [comment]
Not sure what you're asking.. 

Also worth noting that not all ajax select scenarios return models
Could also be used for state => city => town | product => available sizes
