### ISSUE TITLE
Translate 'Choose an option'

### ISSUE THREAD

**Issue by preliot** [dillingham/nova-ajax-select#5]
First option in ajax select is 'Choose an option'. How do i translate this? 

Tried a vendor translation, but this doesn't work:

/resources/vendor/nova-ajax-select/nl.json

 `{
  "Choose an option": "Maak een keuze"
}`

**Comment by dillingham** [comment]
@preliot Thanks, Ill look into adding this soon

**Comment by preliot** [comment]
Thanks @dillingham

**Comment by dillingham** [comment]
@preliot published this in 1.0.3 :)

**Comment by preliot** [comment]
Thanks @dillingham . Excellent support 👍

**Comment by preliot** [comment]
Translatable text should be placed in /resources/lang/vendor/nova/**language**.json. (Replace **language** with your language.

Following items can be translated:

"Choose an option"
"No Results"
