### ISSUE TITLE
Request: autoselect single option

### ISSUE THREAD

**Issue by preliot** [dillingham/nova-ajax-select#6]
Would be great if one option is returned and the field is required, this option is auto-selected. I would consider this better UX.

**Comment by dillingham** [comment]
@preliot thanks for the feedback but because some selects may be optional.. I have to disagree.

**Comment by preliot** [comment]
But what about a **required** select?

**Comment by dillingham** [comment]
The default nova select behavior doesn't do this
Therefore would be out of place if a 3rd party did it

**Comment by preliot** [comment]
I'm using it like this:

` return \NovaAjaxSelect\AjaxSelect::make('Clients', 'client')
->get(config('nova.path') . '/distributors/{distributor}/clients')
->parent('distributor')
->rules('required');  
`

But i understand now what you are saying; it's a rule and not default behaviour for the select.

**Comment by preliot** [comment]
Because it's important to my project, bare with me...

How about this? A select has a nullable() method, like (all) fields do. If a select is **not** nullable and there's one option, the user must select this option. This currently happens in my project, hence my efforts to convince :-)
