### ISSUE TITLE
Request: feedback when no options are available

### ISSUE THREAD

**Issue by preliot** [dillingham/nova-ajax-select#7]
If no options are returned, the user gets no response. 

For example: Say i have a company with several departments. One department is missing workers. When i select that department, nothing happens. 

Would be nice if the text 'Choose an option' changes to 'No options'.

**Comment by dillingham** [comment]
@preliot Thanks, Ill look into adding this soon

**Comment by preliot** [comment]
@dillingham Much appreciated

**Comment by dillingham** [comment]
@preliot published this in 1.0.3 :)

**Comment by preliot** [comment]
Again, thanks for your efforts.
